spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test #配置h2数据库的连接地址
    username: sa
    password: sa
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations:  classpath:db/data-h2.sql
  h2:
    console:
      enabled: true
      path: /h2-console

auth.jwt.secretKey: 123456
auth.jwt.validityInMs: 604800000